myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('resume/', include('resume.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("admin/", admin.site.urls),
    path("education", views.education, name="education"),
    path("experience", views.experience, name="experience"),
    path(
        "experience/<int:pk>", views.individual_experience, name="individual_experience"
    ),
    path("projects", views.projects, name="projects"),
    path("projects/<int:pk>", views.individual_projects, name="individual_projects"),
    path("skills", views.skills, name="skills"),
    path("skills/<int:pk>", views.individual_skills, name="individual_skills"),
    path("502", views.test_502_error, name="502 Error"),
]

resume/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
import boto3
from datetime import date

animations = [
    ("back", "Back"),
    ("forward", "Forward"),
    ("down", "Down"),
    ("up", "Down"),
    ("spin", "Spin"),
    ("drop", "Drop"),
    ("fade", "Fade"),
    ("float-away", "Float Away"),
    ("sink-away", "Sink Away"),
    ("grow", "Grow"),
    ("shrink", "Shrink"),
    ("pulse", "Pulse"),
    ("pulse-grow", "Pulse Grow"),
    ("pulse-shrink", "Pulse Shrink"),
    ("push", "Push"),
    ("pop", "Pop"),
    ("bounce", "Bounce"),
    ("rotate", "Rotate"),
    ("grow-rotate", "Grow Rotate"),
    ("float", "Float"),
    ("sink", "Sink"),
    ("bob", "Bob"),
    ("hang", "Hang"),
    ("wobble-horizontal", "Wobble Horizontal"),
    ("wobble-vertical", "Wobble Vertical"),
    ("buzz", "Buzz"),
    ("buzz-out", "Buzz Out"),
]


# Validators
def date_validator_past_only(value):
    if value > date.today():
        raise ValidationError("Only Dates in the Past Are Allowed")


def date_validator_future_only(value):
    if value < date.today():
        raise ValidationError("Only Dates in the Future Are Allowed")


# Utilities
def overwrite_db(file_name, bucket, object_name=None):
    """Upload a file to an S3 bucket

    :param file_name: File to upload
    :param bucket: Bucket to upload to
    :param object_name: S3 object name. If not specified then file_name is used
    :return: True if file was uploaded, else False
    """

    # If S3 object_name was not specified, use file_name
    if object_name is None:
        object_name = file_name

    # Upload the file
    s3_client = boto3.client("s3")
    s3_client.upload_file(file_name, bucket, object_name)


# Create your models here.
class Education(models.Model):
    id = models.AutoField(primary_key=True)
    university = models.CharField(max_length=140, verbose_name="Name of University")
    college = models.CharField(max_length=140, verbose_name="College")
    degree = models.CharField(max_length=140, verbose_name="Type of Degree")
    major = models.CharField(
        max_length=140, verbose_name="Major", null=True, blank=True
    )
    start_year = models.IntegerField(
        verbose_name="Start Year",
        validators=[MinValueValidator(2000), MaxValueValidator(2100)],
    )
    end_year = models.IntegerField(
        verbose_name="End Year",
        null=True,
        blank=True,
        validators=[MinValueValidator(2000), MaxValueValidator(2100)],
    )
    gpa = models.DecimalField(
        decimal_places=2, max_digits=4, default=4.00, verbose_name="GPA"
    )
    banner = models.FileField(default="IMAGE URL", verbose_name="Banner Image")
    logo = models.FileField(default="IMAGE URL", verbose_name="Logo")

    def __str__(self):
        return self.university

    def save(self, *args, **kwargs):
        super(Education, self).save(*args, **kwargs)
        overwrite_db(
            settings.DATABASES["default"]["NAME"],
            settings.AWS_STORAGE_BUCKET_NAME,
            settings.DB_FILE_NAME,
        )


class Experience(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=140, verbose_name="Company Name")
    role = models.CharField(max_length=140)
    start_date = models.DateField(verbose_name="Start Date")
    end_date = models.DateField(verbose_name="End Date", blank=True, null=True)
    current = models.BooleanField(verbose_name="Current Role?", default=False)
    long_description = models.TextField(
        blank=True, null=True, verbose_name="Long Description"
    )
    banner = models.ImageField(verbose_name="Banner Image")
    tile = models.ImageField(verbose_name="Tile Image")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.current and not kwargs.pop("chain", False):
            for obj in self.__class__.objects.exclude(pk=self.pk):
                if obj.current:
                    obj.current = False
                    obj.save()
        super(Experience, self).save(*args, **kwargs)
        overwrite_db(
            settings.DATABASES["default"]["NAME"],
            settings.AWS_STORAGE_BUCKET_NAME,
            settings.DB_FILE_NAME,
        )


class Projects(models.Model):
    id = models.AutoField(primary_key=True)
    industry = models.CharField(max_length=140)
    overview = models.CharField(max_length=300)
    start_date = models.DateField(verbose_name="Start Date", blank=True, null=True)
    end_date = models.DateField(verbose_name="End Date", blank=True, null=True)
    long_description = models.TextField()
    skills = models.ManyToManyField("Skills")

    def __str__(self):
        return f"{self.industry}: {self.overview}"

    def save(self, *args, **kwargs):
        super(Projects, self).save(*args, **kwargs)
        overwrite_db(
            settings.DATABASES["default"]["NAME"],
            settings.AWS_STORAGE_BUCKET_NAME,
            settings.DB_FILE_NAME,
        )


class Classes(models.Model):
    id = models.AutoField(primary_key=True)
    school = models.ForeignKey(Education, on_delete=models.CASCADE)
    subject = models.CharField(max_length=5)
    course_number = models.CharField(max_length=5)
    course_name = models.CharField(max_length=140)
    credit_hours = models.CharField(max_length=1)

    def __str__(self):
        return self.course_name

    def save(self, *args, **kwargs):
        super(Classes, self).save(*args, **kwargs)
        overwrite_db(
            settings.DATABASES["default"]["NAME"],
            settings.AWS_STORAGE_BUCKET_NAME,
            settings.DB_FILE_NAME,
        )


class Skills(models.Model):
    id = models.AutoField(primary_key=True)
    skill = models.CharField(max_length=40)
    frameworks = models.TextField()
    logo = models.FileField(verbose_name="Language Logo")
    hover_animation = models.CharField(
        max_length=40, blank=True, null=True, choices=animations
    )

    def __str__(self):
        return self.skill

    def save(self, *args, **kwargs):
        super(Skills, self).save(*args, **kwargs)
        overwrite_db(
            settings.DATABASES["default"]["NAME"],
            settings.AWS_STORAGE_BUCKET_NAME,
            settings.DB_FILE_NAME,
        )


class Certifications(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=140)
    vendor = models.CharField(max_length=60)
    acquired = models.DateField(
        verbose_name="Acquisiton Date of the Certificate",
        validators=[date_validator_past_only],
    )
    expire = models.DateField(
        verbose_name="Expiration Date of the Certificate",
        validators=[date_validator_future_only],
    )
    icon = models.FileField(blank=True, null=True)

    def __str__(self):
        return "{} {}".format(self.vendor, self.name)

    def save(self, *args, **kwargs):
        super(Certifications, self).save(*args, **kwargs)
        overwrite_db(
            settings.DATABASES["default"]["NAME"],
            settings.AWS_STORAGE_BUCKET_NAME,
            settings.DB_FILE_NAME,
        )

resume/forms.py
from django import forms
from resume.widgets import MonthYearWidget


class MonthYearForm(forms.Form):
    date = forms.DateField(widget=MonthYearWidget)

resume/views.py
from django.shortcuts import render
from django.http import HttpResponse
import logging
from datetime import date
from resume.models import Classes, Skills, Certifications, Education, Projects \
    , Experience


logger = logging.getLogger("django")


def index(request):
    # Sorting the experiences so the most recent will be first, if
    # there is no end date then create a future date and use that
    experiences = sorted(
        Experience.objects.all(),
        reverse=True,
        key=lambda x: x.end_date or date(2069, 4, 20),
    )
    projects = sorted(
        Projects.objects.all(),
        reverse=True,
        key=lambda x: x.end_date or date(2069, 4, 20),
    )
    education = Education.objects.all()
    skills = Skills.objects.all()
    certifications = Certifications.objects.all()
    try:
        current = Experience.objects.get(current=True)
    except Experience.DoesNotExist:
        current = None

    data = {
        "current": current,
        "experiences": experiences,
        "projects": projects,
        "education": education,
        "skills": skills,
        "certifications": certifications,
    }

    return render(request, "resume/resume.html", data)


def education(request):
    education = Education.objects.all().order_by("-pk")
    data = {
        "education": education,
        "classes": Classes.objects.all(),
    }

    return render(request, "resume/education.html", data)


def experience(request):
    data = {
        "experiences": sorted(
            Experience.objects.all(),
            reverse=True,
            key=lambda x: x.end_date or date(2069, 4, 20),
        ),
    }

    return render(request, "resume/experience.html", data)


def individual_experience(request, pk):
    data = {
        "position": Experience.objects.filter(pk=pk)[0]
    }

    return render(request, "resume/experience_individual.html", data)


def projects(request):
    data = {
        "projects": sorted(
            Projects.objects.all(),
            reverse=True,
            key=lambda x: x.end_date or date(2069, 4, 20),
        )
    }

    return render(request, "resume/projects.html", data)


def individual_projects(request, pk):
    data = {
        "project": Projects.objects.filter(pk=pk)[0]
    }

    return render(request, "resume/individual_project.html", data)


def skills(request):
    data = {
        "skills": Skills.objects.all()
    }

    return render(request, "resume/skills.html", data)


def individual_skills(request, pk):
    data = {
        "skill": Skills.objects.filter(pk=pk)[0]
    }

    return render(request, "resume/individual_skill.html", data)


# For Testing Purposes


def test_502_error(request):
    return HttpResponse(status=502)

resume/templates/resume/education.html
{% extends "resume/header.html" %}
{% load static %}

{% block contentlinks %}
<link type="text/css" rel="stylesheet" href="{% static 'resume/css/education.css' %}">
{% endblock %}

{% block content %}
<section class="body">
  <h1 class="body-title-text">Education</h1>
  <div class="education-container">
    {% for entry in education %}
    <div class="education-school">
      <img class="education-banner" src="{{ entry.banner.url }}">
      <img class="education-logo" src="{{ entry.logo.url }}">
      <div class="education-text">
        <p>{{ entry.university }}</p>
        <p>{{ entry.college }}</p>
        <p>{{ entry.degree }} in {{ entry.major }}</p>
        <p>Class of {{ entry.year }}</p>
        <p>GPA {{ entry.gpa }}/4</p>
      </div>
    </div>
    <p class="education-coursework">Coursework</p>
    <ul class="education-courses">
      {% for class in entry.classes_set.all %}
      {% if class.school_id == entry.id %}
      <li>{{class.course_number}} {{class.subject}} {{class.course_name}}</li>
      {% endif %}
      {% endfor %}
    </ul>
    {% endfor %}
  </div>
  <div class="space"></div>
</section>
{% endblock %}

resume/templates/resume/experience.html
{% extends "resume/header.html" %}
{% load static %}

{% block contentlinks %}
<link type="text/css" rel="stylesheet" href="{% static 'resume/css/experience.css' %}">
{% endblock %}

{% block content %}
<section class="body">
  <h1 class="body-title-text">Experience</h1>
  <div class='experiences-container'>
    {% for entry in experiences %}
      <a class="body-card experiences-experience" href="experience/{{ entry.pk }}">
        <img class="experiences-banner" src="{{ entry.banner.url }}">
        <div class="experiences-text">
          <p>{{ entry.name }}</p>
          <p>{{ entry.role }}</p>
          <p>{{ entry.start_date|date:"F Y" }} - 
            {% if entry.end_date %}
              {{ entry.end_date|date:"F Y" }}
            {% else %}
              {{ "Present" }}
            {% endif %}
          </p>
        </div>
      </a>
    {% endfor %}
  </div>
  <div class="space"></div>
</section>
{% endblock %}

resume/templates/resume/experience_individual.html
{% extends "resume/header.html" %}
{% load static %}

{% block contentlinks %}
<link type="text/css" rel="stylesheet" href="{% static 'resume/css/experience.css' %}">
{% endblock %}

{% block content %}
<section class="body">
  <h1 class="body-title-text">Experience</h1>
  <div class="experience">
      <div class="experience-text">
          <p class="experience-name">{{ position.name }}</p>
          <p>{{ position.role }}</p>
          {% if position.duration %}
              <p>{{ position.duration }}</p>
          {% endif %}
      </div>
      
      <img class="experience-banner" src="{{ position.banner.url }}">
      <div class="experience-description-wrapper">
          <img class="experience-tile" src="{{ position.tile.url }}">
          <div class="experience-description">{{ position.long_description|linebreaks }}</div>
      </div>
  </div>
  <div class="space"></div>
</section>
{% endblock %}

resume/templates/resume/header.html
{% extends "menu.html" %}
{% load static %}

{% block headerlinks %}
<link rel="stylesheet" type="text/css" href="{% static 'resume/css/header.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'resume/css/Hover/Hover-master/css/hover.css' %}">
<link href="https://fonts.googleapis.com/css?family=Aguafina+Script|Allura|Cormorant+Garamond|Courgette&display=swap" rel="stylesheet">
{% block contentlinks %}
{% endblock %}
{% endblock %}

{% block body %}
<body>
  <header>
    <div class="header-banner-image" style="background: url({% static 'resume/images/Header.jpg' %}); background-size: 100% 100%;">
      <h1 class="header-location">Atlanta, Georgia</h1>
      <div class="header-menubar">
        <div class="header-title">Michael Scully</div>
        <div class="header-menu-items">
          <a class="header-buttons" href="/resume">Resume</a>
          <a class="header-buttons" href="/resume/education">Education</a>
          <a class="header-buttons" href="/resume/experience">Experience</a>
          <a class="header-buttons" href="/resume/projects">Projects</a>
          <a class="header-buttons" href="/resume/skills">Skills</a>
        </div>
      </div>
    </div>
  </header>
  {% block content %}
  {% endblock %}
  <footer class="footer">
    <p class="footer-credits">Design by Michael Scully</p>
    <p class="footer-credits"><a class="footer-links" href="mailto:michael.scully1997@gmail.com">Contact Me</p>
    <p class="footer-credits">Animations done using <a href="http://ianlunn.github.io/Hover/" class="footer-links">Hover.css</a></p>
    <p class="footer-credits">Running on Django 3</p>
  </footer>
  {% block extrafoot %}
  {% endblock %}
</body>
{% endblock %}

resume/templates/resume/individual_experience.html
{% extends "resume/header.html" %}
{% load static %}

{% block contentlinks %}
<link type="text/css" rel="stylesheet" href="{% static 'resume/css/experience.css' %}">
{% endblock %}

{% block content %}
<section class="body">
  <h1 class="body-title-text">Experience</h1>
  <div class="experience">
      <div class="experience-text">
          <p class="experience-name">{{ position.name }}</p>
          <p>{{ position.role }}</p>
          {% if position.duration %}
              <p>{{ position.duration }}</p>
          {% endif %}
      </div>
      
      <img class="experience-banner" src="{{ position.banner.url }}">
      <div class="experience-description-wrapper">
          <img class="experience-tile" src="{{ position.tile.url }}">
          <div class="experience-description">{{ position.long_description|linebreaks }}</div>
      </div>
  </div>
  <div class="space"></div>
</section>
{% endblock %}

resume/templates/resume/individual_project.html
{% extends 'resume/header.html' %}
{% load static %}

{% block contentlinks %}
<link type="text/css" rel="stylesheet" href="{% static 'resume/css/projects.css' %}">
<script rel="text/JavaScript" src="{% static 'resume/js/removeCommas.js' %}"></script>
{% endblock %}

{% block content %}
<section class="body">
  <h1 class="body-title-text">Projects</h1>
  <div class="project">
    <div class="project-info-wrapper">
      <div class="project-languages-logos">
        {% for skill in project.skills.all %}
          <img class="project-languages-logo" src="{{ skill.logo.url }}">
        {% endfor %}
      </div>
      <div class="project-text">
        <p>{{ project.industry }}</p>
        <p>{{ project.role }}</p>
        <p>{{ project.overview }}</p>
        <p>
          {{ project.start_date|date:"F Y" }} - 
          {% if project.end_date %}
            {{ project.end_date|date:"F Y" }}
          {% else %}
            {{ "Present" }}
          {% endif %}
        </p>
      </div>
    </div>
    <div class="project-description">{{ project.long_description | linebreaks}}</div>
  </div> 
  <div class="space"></div>
</section>
{% endblock %}

resume/templates/resume/individual_skill.html
{% extends "resume/header.html" %}
{% load static %}

{% block contentlinks %}
<link type="text/css" rel="stylesheet" href="{% static 'resume/css/skills.css' %}">
{% endblock %}

{% block content %}
<section class="body">
  <h1 class="body-title-text">Skills</h1>
  <div class='skill'>
    <p class="skill-name">{{ skill.skill }}</p>
    <img class="skill-logo" src="{{ skill.logo.url }}">
    <div class="skill-projects">
      <p class="skill-projects-header">Projects Using This Skill:</p>
      {% for project in skill.projects_set.all %}
      <a class="skill-project" href="../../resume/projects/{{ project.id }}">{{project.overview}}</a><br>
      {% endfor %}
    </div>
  </div>
  <div class="space"></div>
</section>
{% endblock %}

resume/templates/resume/portfolio.html
{% extends "resume/header.html" %}
{% load static %}

{% block extrahead %}
<link type="text/css" rel="stylesheet" href="{% static 'resume/css/portfolio.css' %}">
<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
<body id="background">
    <div class="box">
        <div class="body-plaque"><h1 class="body-plaque-text">My Portfolio</h1></div>
        <table class="investments" cellpadding="0" cellspacing="0" border="0">
            <col width="100">
            <col width="275">
            <col width="200">
            <col width="150">
            <col width="150">
            <thead>
                <tr style="text-align: left;">
                    <th>Ticker</th>
                    <th>Name</th>
                    <th>Date of Purchase</th>
                    <th>Price Paid</th>
                    <th>Current Price</th>
                </tr>
            </thead>
            <tbody>
            {% for Investments in object_list %}
            <tr class="investment">
                <td class="ticker">{{ Investments.ticker }}</td>
                <td>{{ Investments.name }}</td>
                <td>{{ Investments.date_of_purchase }}</td>
                <td>{{ Investments.price_at_purchase }}</td>
                <td class="price">Loading...</td>
            </tr>
            {%  endfor %}
            </tbody>
        </table>
        </div>
    <div class="space"></div>
</body>
{% endblock %}

{% block extrafoot %}
<script src="{% static 'resume/js/portfolio.js' %}"></script>
{% endblock %}

resume/templates/resume/project_individual.html
{% extends 'resume/header.html' %}
{% load static %}

{% block contentlinks %}
<link type="text/css" rel="stylesheet" href="{% static 'resume/css/projects.css' %}">
<script rel="text/JavaScript" src="{% static 'resume/js/removeCommas.js' %}"></script>
{% endblock %}

{% block content %}
<section class="body">
  <h1 class="body-title-text">Projects</h1>
  <div class="project">
    <div class="project-info-wrapper">
      <div class="project-languages-logos">
        {% for skill in project.skills.all %}
          <img class="project-languages-logo" src="{{ skill.logo.url }}">
        {% endfor %}
      </div>
      <div class="project-text">
        <p>{{ project.industry }}</p>
        <p>{{ project.role }}</p>
        <p>{{ project.overview }}</p>
        <p>
          {{ project.start_date|date:"F Y" }} - 
          {% if project.end_date %}
            {{ project.end_date|date:"F Y" }}
          {% else %}
            {{ "Present" }}
          {% endif %}
        </p>
      </div>
    </div>
    <div class="project-description">{{ project.long_description | linebreaks}}</div>
  </div> 
  <div class="space"></div>
</section>
{% endblock %}

resume/templates/resume/projects.html
{% extends "resume/header.html" %}
{% load static %}

{% block contentlinks %}
<link type="text/css" rel="stylesheet" href="{% static 'resume/css/projects.css' %}">
{% endblock %}

{% block content %}
<section class="body">
  <h1 class="body-title-text">Projects</h1>
  <div class="projects-container">
    {% for entry in projects %}
    <a class="body-card projects-project" href="projects/{{ entry.pk }}">
      <div class="projects-banner" style="grid-template-columns: repeat({{entry.skills.all|length}}, 1fr);">
        {% for skill in entry.skills.all %}
        <img class="projects-languages-logo" src="{{ skill.logo.url }}">
        {% endfor %}
      </div>
      <div class="projects-text">
        <p>{{ entry.industry }}</p>
        <p>{{ entry.role }}</p>
        <p>{{ entry.overview }}</p>
        <p>{{ entry.start_date|date:"F Y" }} -
          {% if entry.end_date %}
          {{ entry.end_date|date:"F Y" }}
          {% else %}
          {{ "Present" }}
          {% endif %}
        </p>
      </div>
    </a>
    {% endfor %}
  </div>
  <div class="space"></div>
</section>
{% endblock %}

resume/templates/resume/resume.html
{% extends "resume/header.html" %}
{% load static %}

{% block contentlinks %}
<link rel="stylesheet" type="text/css" href="{% static 'resume/css/resume.css' %}">
{% endblock %}

{% block content %}
<section class="body">
  <h1 class="body-title-text">Resume</h1>
  <div class="resume-opening">
    <img id="resume-headshot" src="{% static 'resume/images/Headshot.jpg' %}">
    <a href="experience/{{ current.pk }}" class="body-card resume-current">
      <img class="resume-logo" src="{{ current.banner.url }}">
      <div>
        <p class="resume-text">{{ current.name }}</p>
        <p class="resume-text">{{ current.role }}</p>
      </div>
    </a>
  </div>
  <div class="blank">Education</div>

  <div class='resume-educations'>
    {% for entry in education %}
    <a href="education" class="body-card resume-education">
      <img class="resume-logo" src="{{ entry.logo.url }}">
      <div class="resume-text">
        <p>{{ entry.university }}</p>
        <p>{{ entry.degree }} in {{ entry.major }}</p>
        <p>Class of {{ entry.year }}</p>
        <p>GPA: {{ entry.gpa }}</p>
      </div>
    </a>
    {% endfor %}
  </div>


  <div class="blank">Business Experience</div>

  <div class="resume-experiences">
    {% for entry in experiences %}
    <a href="experience/{{ entry.pk }}" class="body-card resume-experience">
      <img class="resume-logo" src="{{ entry.banner.url }}">
      <div class="resume-text">
        <p>{{ entry.name }}</p>
        <p>{{ entry.role }}</p>
        <p>{{ entry.start_date|date:"F Y" }} -
          {% if entry.end_date %}
          {{ entry.end_date|date:"F Y" }}
          {% else %}
          {{ "Present" }}
          {% endif %}
        </p>
      </div>
    </a>
    {% endfor %}
  </div>

  <div class="blank">Projects</div>

  <div class="resume-projects">
    {% for entry in projects %}
    <a href="projects/{{ entry.pk }}" class="resume-project body-card">
      <div class="resume-project-banner" style="grid-template-columns: repeat({{entry.skills.all|length}}, 1fr);">
        {% for skill in entry.skills.all %}
        <img class="resume-logo" src="{{ skill.logo.url }}">
        {% endfor %}
      </div>
      <div class="resume-text">
        <p>{{ entry.industry }}</p>
        <p>{{ entry.overview }}</p>
        <p>{{ entry.start_date|date:"F Y" }} -
          {% if entry.end_date %}
          {{ entry.end_date|date:"F Y" }}
          {% else %}
          {{ "Present" }}
          {% endif %}
        </p>
      </div>
    </a>
    {% endfor %}
  </div>

  <div class="blank">Skills</div>
  <div class="resume-skills">
    {% for skill in skills %}
    <a href="skills/{{ skill.pk }}" class="resume-skill body-card hvr-icon-{{ skill.hover_animation }}">
      <img class="resume-logo hvr-icon" src="{{ skill.logo.url }}">
      <p class="resume-text">{{ skill.skill }}</p>
    </a>
    {% endfor %}
    <div class="space"></div>
  </div>

  <div class="blank">Certifications</div>
  <div class="resume-certifications">
    {% for cert in certifications %}
    <a class="resume-certification body-card">
      <img class="resume-logo" src="{{ cert.icon.url }}">
      <div>
        <p class="resume-text">{{ cert.vendor }} {{cert.name}}</p>
      </div>
    </a>
    {% endfor %}
  </div>
  <div class="space"></div>
</section>
{% endblock %}

resume/templates/resume/skill_individual.html
{% extends "resume/header.html" %}
{% load static %}

{% block contentlinks %}
<link type="text/css" rel="stylesheet" href="{% static 'resume/css/skills.css' %}">
{% endblock %}

{% block content %}
<section class="body">
  <h1 class="body-title-text">Skills</h1>
  <div class='skill'>
    <p class="skill-name">{{ skill.skill }}</p>
    <img class="skill-logo" src="{{ skill.logo.url }}">
    <div class="skill-projects">
      <p class="skill-projects-header">Projects Using This Skill:</p>
      {% for project in skill.projects_set.all %}
      <a class="skill-project" href="../../resume/projects/{{ project.id }}">{{project.overview}}</a><br>
      {% endfor %}
    </div>
  </div>
  <div class="space"></div>
</section>
{% endblock %}

resume/templates/resume/skills.html
{% extends "resume/header.html" %}
{% load static %}

{% block contentlinks %}
<link type="text/css" rel="stylesheet" href="{% static 'resume/css/skills.css' %}">
<!-- <script rel="text/JavaScript" src="{% static 'resume/js/resizingCards.js' %}"></script> -->
{% endblock %}

{% block content %}
<section class="body">
  <h1 class="body-title-text">Skills</h1>
  <div class="skills-container">
    {% for skill in skills %}
    <a href="skills/{{ skill.pk }}" class="skills-skill body-card hvr-icon-{{ skill.hover_animation }}">
      <img class="skills-logo hvr-icon" src="{{ skill.logo.url }}">
      <p class="skills-text">{{ skill.skill }}</p>
    </a>
    {% endfor %}
  </div>
  <div class="space"></div>
</section>
{% endblock %}